# ─── Keybind Config ───────────────────────────────────────────────────────────
# Set Ctrl-z to send-prefix
unbind C-b
set-option -g prefix C-z
bind-key C-z send-prefix

# Reload config
unbind r
bind r source-file ~/.tmux.conf

# Open new windows in current path
unbind N
bind N new-window -c "#{pane_current_path}"

# Open new panes in current path
unbind H
bind H split-window -h -c "#{pane_current_path}"
unbind J
bind J split-window -v -c "#{pane_current_path}"

# Rename current window & session
unbind W
bind W command-prompt -I "#W" { rename-window "%%" }
unbind S
bind S command-prompt -I "#S" { rename-session "%%" }

# Close current window
unbind Q
bind Q confirm-before -p "kill-window #W? (y/n)" kill-window

# keyring
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-j select-pane -D
bind -n M-k select-pane -U

# ─── Tmux Options ─────────────────────────────────────────────────────────────
set -g mouse on    # Enable mouse in tmux
set -g base-index 1
set -g pane-base-index 1
set -g set-clipboard on
#set -g status-position top
set -g status-position bottom
set -g default-terminal "tmux-256color"
#set -g terminal-overrides ",*:RGB"
set -g escape-time 15
set -g renumber-windows on

set -g allow-passthrough on
set -g extended-keys always
#set -g @plugin 'catppuccin/tmux#v2.1.3' # See https://github.com/catppuccin/tmux/tags for additional tags
#set -g @plugin 'tmux-plugins/tpm'

# ─── Plugins ──────────────────────────────────────────────────────────────────
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'viegphunt/catppuccin-tmux'
# latte\frappe\macchiato\mocha
set -g @catppuccin_flavor 'mocha'


# ─── Window Styling ───────────────────────────────────────────────────────────
set -g window-status-separator "|"
set -g status-left-length 0
set -g @catppuccin_status_background "none"
set -g status-left " #{?client_prefix,#[fg=#{@thm_red} bold],#{?#{==:#{pane_mode},copy-mode},#[fg=#{@thm_yellow} bold],#[fg=#{@thm_green} bold]}}TMUX #[fg=#{@thm_fg} bold]| "
set -g @catppuccin_window_number_position "left"
set -g @catppuccin_window_current_number_color "#{@thm_primary}"
#set -g @catppuccin_window_current_number "#[bold]#I: #W  "
set -g @catppuccin_window_current_text ""
set -g @catppuccin_window_number_color "#{@thm_surface_0}"
set -g @catppuccin_window_number "#[fg=#{@thm_fg} bold]#I: #W  "
set -g @catppuccin_window_text ""
set -g @catppuccin_window_status_style "basic"
set -g status-right "#[fg=#{@thm_peach} bold] [#S] #[fg=#{@thm_fg} bold]| "
set -ga status-right "#[fg=#{@thm_blue} bold]󰃰 %a %d/%m/%Y ~ %H:%M "

# ---- Make the status line pretty and add some modules -----------------------
#set -g status-right-length 100
#set -g status-left-length 100
#set -g status-left ""
#set -g status-right "#{E:@catppuccin_status_application}"
#set -agF status-right "#{E:@catppuccin_status_cpu}"
#set -ag status-right "#{E:@catppuccin_status_session}"
#set -ag status-right "#{E:@catppuccin_status_uptime}"
#set -agF status-right "#{E:@catppuccin_status_battery}"

#run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux
#run ~/.config/tmux/plugins/tmux-plugins/tmux-battery/battery.tmux

# ─── Initialize Plugins ───────────────────────────────────────────────────────
source-file ~/.config/tmux/matugen-colors.conf
# Initialize TMUX plugin manager (keep this line at the very botto of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'

source ~/.config/tmux/user/matugen-catppuccin.conf


# matugen dynamic colors (auto-generated)

