cursor #c8c3dc
cursor_text_color #c9c5d0

foreground            #e5e1e9
background            #141318
selection_foreground  #302e41
selection_background  #c8c3dc
url_color             #c6bfff

# black
color8   #928f99
color0   #4c4c4c

# red
color1   #ac8a8c
color9   #c49ea0

# green (与 blue 同色，跟随主色)
color2   #c6bfff
color10  #a39ec4

# yellow
color3   #aca98a
color11  #c4c19e

# blue
color4  #c6bfff
color12 #a39ec4

# magenta
color5   #ebb8cf
color13  #ffd8e8

# cyan (绑定次要色，利用 fixed_dim 原生实现“调暗”效果，杜绝渲染报错)
color6   #c8c3dc
color14  #c8c3dc

# white
color15  #e7e7e7
color7   #f0f0f0
