# Matugen generated tmux options for catppuccin-tmux
set -g @thm_bg "#211e24"
set -g @thm_fg "#e7e0e8"
set -g @thm_surface_0 "#2c292f"
set -g @thm_primary "#d5bbfc"
set -g @thm_secondary "#cec2db"
set -g @thm_tertiary "#f1b7c3"
set -g @thm_red "#ffb4ab"
set -g @thm_yellow "#f1b7c3"
set -g @thm_green "#cec2db"
set -g @thm_peach "#d5bbfc"
set -g @thm_blue "#342d40"
