[general]
bars = 24
framerate = 10
autosens = 1
sensitivity = 80

[input]
method = pipewire

[output]
method = raw
data_format = ascii
ascii_max = 100
ascii_delimiter = ;
channels = mono
raw_target = /dev/stdout
