# FZF Colors - Generated by Matugen
export FZF_DEFAULT_OPTS=" \
--color=bg+:#{{colors.surface_container_high.default.hex_stripped}},spinner:#{{colors.on_primary_container.default.hex_stripped}},hl:#{{colors.primary.default.hex_stripped}} \
--color=fg:#{{colors.on_surface.default.hex_stripped}},header:#{{colors.primary.default.hex_stripped}},info:#{{colors.tertiary.default.hex_stripped}},pointer:#{{colors.on_primary_container.default.hex_stripped}} \
--color=marker:#{{colors.secondary.default.hex_stripped}},fg+:#{{colors.on_surface.default.hex_stripped}},prompt:#{{colors.tertiary.default.hex_stripped}},hl+:#{{colors.primary.default.hex_stripped}} \
--color=selected-bg:#{{colors.surface_container.default.hex_stripped}} \
--color=border:#{{colors.outline.default.hex_stripped}},label:#{{colors.on_surface.default.hex_stripped}}"
