  default_color = '{{colors.on_surface_variant.default.hex}}',
  default_outline_color = '{{colors.on_surface_variant.default.hex}}',
  default_shade_color = '{{colors.on_surface_variant.default.hex}}',
  color1 = '{{colors.primary.default.hex}}',
  color2 = '{{colors.secondary.default.hex}}',
  color3 = '{{colors.on_surface_variant.default.hex}}',
