-- Auto-generated by matugen -- DO NOT EDIT BY HAND
-- astroui 状态栏/标签栏 buffer 配色（跟随壁纸）
-- 用法见 ~/.config/nvim/lua/plugins/astroui.lua 中的 status.colors 函数
return {
  -- 普通不可见 buffer 的文字
  buffer_fg = "{{colors.on_surface_variant.default.hex}}",
  -- 当前聚焦 buffer（主题色背景）
  buffer_active_bg = "{{colors.primary.default.hex}}",
  buffer_active_fg = "{{colors.on_primary.default.hex}}",
  -- 可见但未聚焦 buffer（同色系弱化版）
  buffer_visible_bg = "{{colors.primary_container.default.hex}}",
  buffer_visible_fg = "{{colors.on_primary_container.default.hex}}",
  -- 路径颜色（在主题色背景上仍需可读）
  buffer_path_fg = "{{colors.outline.default.hex}}",
  buffer_active_path_fg = "{{colors.on_primary_fixed_variant.default.hex}}",
  buffer_visible_path_fg = "{{colors.outline.default.hex}}",
}
