# Matugen generated tmux options for catppuccin-tmux
set -g @thm_bg "{{colors.surface_container.default.hex}}"
set -g @thm_fg "{{colors.on_surface.default.hex}}"
set -g @thm_surface_0 "{{colors.surface_container_high.default.hex}}"
set -g @thm_primary "{{colors.primary.default.hex}}"
set -g @thm_secondary "{{colors.secondary.default.hex}}"
set -g @thm_tertiary "{{colors.tertiary.default.hex}}"
set -g @thm_red "{{colors.error.default.hex}}"
set -g @thm_yellow "{{colors.tertiary.default.hex}}"
set -g @thm_green "{{colors.secondary.default.hex}}"
set -g @thm_peach "{{colors.primary.default.hex}}"
set -g @thm_blue "{{colors.on_secondary.default.hex}}"
